(function ensightenInit(){var ensightenOptions = {client: "williamhill", clientId: 154, publishPath: "esmob", isPublic:0, serverComponentLocation: "nexus.ensighten.com/williamhill/esmob/serverComponent.php", staticJavascriptPath: "nexus.ensighten.com/williamhill/esmob/code/", ns: 'Bootstrapper', nexus:"nexus.ensighten.com", scUseCacheBuster: "true", enableTagAuditBeacon : "false", enablePagePerfBeacon : "false", registryNs : "ensBootstraps", generatedOn : "Thu Jul 02 06:30:24 GMT 2015", beaconSamplingSeedValue: 11};
if ( !window[ensightenOptions.ns] ) {
window[ensightenOptions.registryNs]||(window[ensightenOptions.registryNs]={});
window[ensightenOptions.registryNs][ensightenOptions.ns]=window[ensightenOptions.ns]=function(f){function m(a){this.name="DependencyNotAvailableException";this.message="Dependency with id "+a+"is missing"}function n(a){this.name="BeaconException";this.message="There was an error durring beacon initialization";a=a||{};this.lineNumber=a.lineNumber||a.line;this.fileName=a.fileName}function p(){for(var a=b.dataDefinitionIds.length,e=!0,d=0;d<a;d++){var c=b.dataDefinitions[b.dataDefinitionIds[d]];if(!c||
null==c.endRegistration){e=!1;break}}e&&b.callOnDataDefintionComplete()}var c={},b={};b.ensightenOptions=ensightenOptions;b.scDataObj={};c.version="1.26.0";c.nexus=f.nexus||"nexus.ensighten.com";c.rand=-1;c.currSec=(new Date).getSeconds();c.options={interval:f.interval||100,erLoc:f.errorLocation||c.nexus+"/error/e.gif",scLoc:f.serverComponentLocation||c.nexus+"/"+f.client+"/serverComponent.php",sjPath:f.staticJavascriptPath||c.nexus+"/"+f.client+"/code/",alLoc:f.alertLocation||c.nexus+"/alerts/a.gif",
publishPath:f.publishPath,isPublic:f.isPublic,client:f.client,clientId:f.clientId,enableTagAuditBeacon:f.enableTagAuditBeacon,scUseCacheBuster:f.scUseCacheBuster,beaconSamplingSeedValue:f.beaconSamplingSeedValue||-1};c.ruleList=[];c.allDeploymentIds=[];c.runDeploymentIds=[];c.exceptionList=[];c.ensightenVariables={};c.test=function(a){if(!(a.executionData.hasRun||a.executionData.runTime&&0<a.executionData.runTime.length)){for(var b=0;b<a.dependencies.length;b++)if(!1===a.dependencies[b]())return;
a.execute()}};m.prototype=Error();m.prototype||(m.prototype={});m.prototype.constructor=m;c.DependencyNotAvailableException=m;n.prototype=Error();n.prototype||(n.prototype={});n.prototype.constructor=n;c.BeaconException=n;c.checkForInvalidDependencies=function(a,e,d,l){for(a=0;a<d.length;a++)if("DEPENDENCYNEVERAVAILABLE"===d[a])return b.currentRuleId=this.id,b.currentDeploymentId=this.deploymentId,b.reportException(new c.DependencyNotAvailableException(l[a])),e&&-1!==e&&c.allDeploymentIds.push(e),
!0;return!1};b.currentRuleId=-1;b.currentDeploymentId=-1;b.reportedErrors=[];b.reportedAlerts=[];b.AF=[];b._serverTime="";b._clientIP="";b.sampleBeacon=function(){var a=!1;try{var b=(c.currSec||0)%20,d=c.options.beaconSamplingSeedValue;-1===d?a=!0:0!==b&&0===d%b&&(a=!0)}catch(l){}return a};b.getServerComponent=function(a){b.callOnGetServerComponent();b.insertScript(window.location.protocol+"//"+c.options.scLoc,!1,a||!0,c.options.scUseCacheBuster)};b.setVariable=function(a,b){c.ensightenVariables[a]=
b};b.getVariable=function(a){return a in c.ensightenVariables?c.ensightenVariables[a]:null};b.testAll=function(){for(var a=0;a<c.ruleList.length;a++)c.test(c.ruleList[a])};b.executionState={DOMParsed:!1,DOMLoaded:!1,dataDefinitionComplete:!1,conditionalRules:!1,readyForServerComponent:!1};b.reportException=function(a){a.timestamp=(new Date).getTime();c.exceptionList.push(a);a=window.location.protocol+"//"+c.options.erLoc+"?msg="+encodeURIComponent(a.message||"")+"&lnn="+encodeURIComponent(a.lineNumber||
a.line||-1)+"&fn="+encodeURIComponent(a.fileName||"")+"&cid="+encodeURIComponent(c.options.clientId||-1)+"&client="+encodeURIComponent(c.options.client||"")+"&publishPath="+encodeURIComponent(c.options.publishPath||"")+"&rid="+encodeURIComponent(b.currentRuleId||-1)+"&did="+encodeURIComponent(b.currentDeploymentId||-1)+"&errorName="+encodeURIComponent(a.name||"");a=b.imageRequest(a);a.timestamp=(new Date).getTime();this.reportedErrors.push(a)};b.Rule=function(a){this.execute=function(){this.executionData.runTime.push(new Date);
b.currentRuleId=this.id;b.currentDeploymentId=this.deploymentId;try{this.code()}catch(a){window[ensightenOptions.ns].reportException(a)}finally{this.executionData.hasRun=!0,-1!==this.deploymentId&&c.runDeploymentIds.push(this.deploymentId),b.testAll()}};this.id=a.id;this.deploymentId=a.deploymentId;this.dependencies=a.dependencies||[];this.code=a.code;this.executionData={hasRun:!1,runTime:[]}};b.registerRule=function(a){if(b.getRule(a.id)&&-1!==a.id)return!1;c.ruleList.push(a);-1!==a.deploymentId&&
c.allDeploymentIds.push(a.deploymentId);b.testAll();return!0};b.getRule=function(a){for(var b=0;b<c.ruleList.length;b++)if(c.ruleList[b].id===a)return c.ruleList[b];return!1};

b.getAllDeploymentIds=function(){return c.allDeploymentIds};b.getRunDeploymentIds=function(){return c.runDeploymentIds};b.hasRuleRun=function(a){return(a=b.getRule(a))?a.executionData.hasRun:!1};c.toTwoChar=function(a){return(2===a.toString().length?
"":"0")+a};b.Alert=function(a){var b=new Date,b=b.getFullYear()+"-"+c.toTwoChar(b.getMonth())+"-"+c.toTwoChar(b.getDate())+" "+c.toTwoChar(b.getHours())+":"+c.toTwoChar(b.getMinutes())+":"+c.toTwoChar(b.getSeconds());this.severity=a.severity||1;this.subject=a.subject||"";this.type=a.type||1;this.ruleId=a.ruleId||-1;this.severity=encodeURIComponent(this.severity);this.date=encodeURIComponent(b);this.subject=encodeURIComponent(this.subject);this.type=encodeURIComponent(this.type)};b.generateAlert=function(a){a=
b.imageRequest(window.location.protocol+"//"+c.options.alLoc+"?d="+a.date+"&su="+a.subject+"&se="+a.severity+"&t="+a.type+"&cid="+c.options.clientId+"&client="+c.options.client+"&publishPath="+c.options.publishPath+"&rid="+b.currentRuleId+"&did="+b.currentDeploymentId);a.timestamp=(new Date).getTime();this.reportedAlerts.push(a)};b.imageRequest=function(a){var b=new Image(0,0);b.src=a;return b};b.insertScript=function(a,e,d,l){var h=document.getElementsByTagName("script"),g;l=void 0!==l?l:!0;if(void 0!==
e?e:1)for(g=0;g<h.length;g++)if(h[g].src===a&&h[g].readyState&&/loaded|complete/.test(h[g].readyState))return;if(d){d=1==d&&"object"==typeof b.scDataObj?b.scDataObj:d;c.rand=Math.random()*("1E"+(10*Math.random()).toFixed(0));e=window.location.href;if("object"===typeof d)for(g in d){g=~e.indexOf("#")?e.slice(e.indexOf("#"),e.length):"";e=e.slice(0,g.length?e.length-g.length:e.length);e+=~e.indexOf("?")?"&":"?";for(k in d)e+=k+"="+d[k]+"&";e=e.slice(0,-1)+g;break}a+="?";l&&(a+="r="+c.rand+"&");a+="ClientID="+
encodeURIComponent(c.options.clientId)+"&PageID="+encodeURIComponent(e)}(function(a,b,e){var d=b.head||b.getElementsByTagName("head");setTimeout(function(){if("item"in d){if(!d[0]){setTimeout(arguments.callee,25);return}d=d[0]}var a=b.createElement("script");a.src=e;a.onload=a.onerror=function(){this.addEventListener&&(this.readyState="loaded")};d.insertBefore(a,d.firstChild)},0)})(window,document,a)};b.loadScriptCallback=function(a,b,d){var c=document.getElementsByTagName("script"),h;d=c[0];for(h=
0;h<c.length;h++)if(c[h].src===a&&c[h].readyState&&/loaded|complete/.test(c[h].readyState))try{b()}catch(g){window[ensightenOptions.ns].reportException(g)}finally{return}c=document.createElement("script");c.type="text/javascript";c.async=!0;c.src=a;c.onerror=function(){this.addEventListener&&(this.readyState="loaded")};c.onload=c.onreadystatechange=function(){if(!this.readyState||"complete"===this.readyState||"loaded"===this.readyState){this.onload=this.onreadystatechange=null;this.addEventListener&&
(this.readyState="loaded");try{b.call(this)}catch(a){window[ensightenOptions.ns].reportException(a)}}};d.parentNode.insertBefore(c,d)};b.unobtrusiveAddEvent=function(a,b,d){try{var c=a[b]?a[b]:function(){};a[b]=function(){d.apply(this,arguments);return c.apply(this,arguments)}}catch(h){window[ensightenOptions.ns].reportException(h)}};b.anonymous=function(a,e){return function(){try{b.currentRuleId=e?e:"anonymous",a()}catch(d){window[ensightenOptions.ns].reportException(d)}}};b.setCurrentRuleId=function(a){b.currentRuleId=
a};b.setCurrentDeploymentId=function(a){b.currentDeploymentId=a};b.bindImmediate=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMParsed=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMParsed}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDOMLoaded=
function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.DOMLoaded}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindPageSpecificCompletion=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.conditionalRules}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};
b.bindOnGetServerComponent=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.readyForServerComponent}],code:a});else if("object"!==typeof a)return!1;b.registerRule(a)};b.bindDataDefinitionComplete=function(a,e,d){if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:d||-1,dependencies:[function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete}],code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)};b.checkHasRun=function(a){if(0===a.length)return!0;for(var e,d=0;d<a.length;++d)if(e=b.getRule(parseInt(a[d],10)),!e||!e.executionData.hasRun)return!1;return!0};b.bindDependencyImmediate=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};
b.bindDependencyDOMLoaded=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMLoaded});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyDOMParsed=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.DOMParsed});
g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.conditionalRules});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===
typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.bindDependencyOnGetServerComponent=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.readyForServerComponent});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==
typeof a)return!1;b.registerRule(a)}};b.bindDependencyPageSpecificCompletion=function(a,e,d,l,h){var g=[];if(!c.checkForInvalidDependencies(e,l,d,h)){g.push(function(){return window[ensightenOptions.ns].executionState.dataDefinitionComplete});g.push(function(){return window[ensightenOptions.ns].checkHasRun(d)});if("function"===typeof a)a=new b.Rule({id:e||-1,deploymentId:l||-1,dependencies:g,code:a});else if("object"!==typeof a)return!1;b.registerRule(a)}};b.dataDefintionIds=[];b.dataDefinitions=
[];b.pageSpecificDataDefinitionsSet=!1;b.setPageSpecificDataDefinitionIds=function(a){for(var e=a.length,d=0;d<e;d++){var c=a[d];if(Array.prototype.indexOf)-1==b.dataDefinitionIds.indexOf(c)&&b.dataDefinitionIds.push(c);else{for(var h=!1,g=b.dataDefinitionIds.length,f=0;f<g;f++)if(b.dataDefinitionIds[f]===c){h=!0;break}h||b.dataDefinitionIds.push(c)}}b.pageSpecificDataDefinitionsSet=!0;p()};b.DataDefinition=function(a,b){this.id=a;this.registrationFn=b;this.endRegistrationTime=this.startRegistrationTime=
null;this.startRegistration=function(){this.startRegistrationTime=new Date};this.endRegistration=function(){this.endRegistrationTime=new Date}};b.registerDataDefinition=function(a,e){var c=b.dataDefinitions[e];c||(c=new b.DataDefinition(e,a),b.dataDefinitions[e]=c);c.startRegistrationTime||(c.startRegistration(),c.registrationFn(),c.endRegistration());b.pageSpecificDataDefinitionsSet&&p()};b.callOnDataDefintionComplete=function(){b.executionState.dataDefinitionComplete=!0;b.testAll()};b.callOnDOMParsed=
function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].testAll()};b.callOnDOMLoaded=function(){window[ensightenOptions.ns].executionState.DOMParsed=!0;window[ensightenOptions.ns].executionState.DOMLoaded=!0;window[ensightenOptions.ns].testAll()};b.callOnPageSpecificCompletion=function(){for(var a=document.getElementsByTagName("script"),b=0,c=a.length;b<c;b++)if(a[b].src.match(/\.ensighten\.com\/(.+?)\/code\/.*/i)&&"loaded"!=a[b].readyState&&"complete"!=a[b].readyState){setTimeout(window[ensightenOptions.ns].callOnPageSpecificCompletion,
50);return}setTimeout(function(){window[ensightenOptions.ns].executionState.conditionalRules=!0;window[ensightenOptions.ns].testAll()},1)};b.callOnGetServerComponent=function(){window[ensightenOptions.ns].executionState.readyForServerComponent=!0;window[ensightenOptions.ns].testAll()};b.hasDOMParsed=function(){return window[ensightenOptions.ns].executionState.DOMParsed};b.hasDOMLoaded=function(){return window[ensightenOptions.ns].executionState.DOMLoaded};b.hasPageSpecificCompletion=function(){return window[ensightenOptions.ns].executionState.conditionalRules};
var q=function(){var a=[],b=!1,c=!1;return{add:function(f){b&&!c?f():"function"==typeof f&&(a[a.length]=f)},exec:function(){c=!0;do{var f=a;a=[];b=!0;for(var h=0;h<f.length;h++)try{f[h].call(window)}catch(g){window[ensightenOptions.ns].reportException(g)}}while(0<a.length);c=!1},haveRun:function(){return b}}};b.new_fArray=function(){return q()};c.timer=null;(function(){function a(a,b){return function(){a.apply(b,arguments)}}window.console||(window.console={});var b=window.console;if(!b.log)if(window.log4javascript){var c=
log4javascript.getDefaultLogger();b.log=a(c.info,c);b.debug=a(c.debug,c);b.info=a(c.info,c);b.warn=a(c.warn,c);b.error=a(c.error,c)}else b.log=function(){};b.debug||(b.debug=b.log);b.info||(b.info=b.log);b.warn||(b.warn=b.log);b.error||(b.error=b.log)})();document.addEventListener?(-1<navigator.userAgent.indexOf("AppleWebKit/")?c.timer=window.setInterval(function(){/loaded|complete/.test(document.readyState)&&(clearInterval(c.timer),b.callOnDOMParsed())},50):document.addEventListener("DOMContentLoaded",
b.callOnDOMParsed,!1),window.addEventListener("load",b.callOnDOMLoaded,!1)):(setTimeout(function(){var a=window.document;(function(){try{if(!document.body)throw"continue";a.documentElement.doScroll("left")}catch(b){setTimeout(arguments.callee,15);return}window[ensightenOptions.ns].callOnDOMParsed()})()},1),window.attachEvent("onload",function(){window[ensightenOptions.ns].callOnDOMLoaded()}));"true"===c.options.enableTagAuditBeacon&&b.sampleBeacon()&&window.setTimeout(function(){if(window[ensightenOptions.ns]&&
!window[ensightenOptions.ns].mobilePlatform)try{for(var a=[],e,d,l,h,g=0;g<c.ruleList.length;++g)d=c.ruleList[g],l=d.executionData.hasRun?"1":"0",h=d.deploymentId.toString()+"|"+d.id.toString()+"|"+l,a.push(h);e="["+a.join(";")+"]";var m=window.location.protocol+"//"+c.nexus+"/"+encodeURIComponent(f.client)+"/"+encodeURIComponent(f.publishPath)+"/TagAuditBeacon.rnc?cid="+encodeURIComponent(f.clientId)+"&data="+e+"&idx=0&r="+c.rand;b.imageRequest(m)}catch(n){b.currentRuleId=-1,b.currentDeploymentId=
-1,a=new c.BeaconException(n),window[ensightenOptions.ns].reportException(a)}},3E3);window.setInterval(b.testAll,c.options.interval);return b}(ensightenOptions);
"true"===ensightenOptions.enablePagePerfBeacon&&window[ensightenOptions.ns]&&window[ensightenOptions.ns].sampleBeacon()&&window[ensightenOptions.ns].bindDOMParsed(function(){if(!window[ensightenOptions.ns].mobilePlatform){var f=window.performance;if(f){var f=f.timing||{},m="",n=f.navigationStart||0,p,c={connectEnd:"ce",connectStart:"cs",domComplete:"dc",domContentLoadedEventEnd:"dclee",domContentLoadedEventStart:"dcles",domInteractive:"di",domLoading:"dl",domainLookupEnd:"dle",domainLookupStart:"dls",
fetchStart:"fs",loadEventEnd:"lee",loadEventStart:"les",redirectEnd:"rede",redirectStart:"reds",requestStart:"reqs",responseStart:"resps",responseEnd:"respe",secureConnectionStart:"scs",unloadEventStart:"ues",unloadEventEnd:"uee"},m="&ns="+encodeURIComponent(f.navigationStart),b;for(b in c)void 0!==f[b]?(p=f[b]-n,m+="&"+c[b]+"="+(0<p?encodeURIComponent(p):0)):m+="&"+c[b]+"=-1";window[ensightenOptions.ns].timing=m;b=ensightenOptions.nexus||"nexus.ensighten.com";f=ensightenOptions.staticJavascriptPath||
"";m=f.indexOf(".com/");n=f.indexOf("/code/");f=f.substring(m+4,n)+"/perf.rnc";f+="?cid="+encodeURIComponent(ensightenOptions.clientId)+window[ensightenOptions.ns].timing;window[ensightenOptions.ns].imageRequest("//"+b+f)}}});
		Bootstrapper.dataDefinitionIds = [];Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.analytics.bannerTracking={smartAppBannerPagename:function(){var page_breakdown=window.location.pathname.split(/\/\w\w(-\w\w)?\//);page_breakdown=page_breakdown[page_breakdown.length-1].replace(/(^payment\/|^)/,"payment/");return page_breakdown},trackSmartAppBannerAction:function(name,action){var pageName=Bootstrapper.analytics.bannerTracking.smartAppBannerPagename();
_t={linkTrackVars:"events,eVar21,prop21",linkTrackEvents:"event9",events:"event9",eVar21:pageName+" - "+name+" - "+action,prop21:pageName+" - "+name+" - "+action,name:"Banner Action"};trk.trackAction(_t,_t.name)},trackSmartAppBannerDisplay:function(name){var pageName=Bootstrapper.analytics.bannerTracking.smartAppBannerPagename();_t={linkTrackVars:"eVar21,prop21",eVar21:pageName+" - "+name+" - Banner Displayed",prop21:pageName+" - "+name+" - Banner Displayed",name:"Banner Displayed"};trk.trackAction(_t,
_t.name)}}},708717,[853020,853021],292957,[148384,150705]);
Bootstrapper.bindDependencyDOMParsed(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;setTimeout(function(){if(document.querySelector&&document.querySelectorAll){var banner=document.querySelector(".sab-container");if(banner!==null&&banner.className.indexOf("ng-hide")===-1){var name="Top Banner";Bootstrapper.analytics.bannerTracking.trackSmartAppBannerDisplay(name);var button=document.querySelector(".sab-container .sab-btn-container a");if(button!==
null)Bootstrapper.unobtrusiveAddEvent(button,"ontouchstart",function(){Bootstrapper.analytics.bannerTracking.trackSmartAppBannerAction(name,button.innerHTML)})}var banner=document.querySelector(".sb-container");if(banner!==null&&banner.className.indexOf("ng-hide")===-1){var name="Overlay Banner";Bootstrapper.analytics.bannerTracking.trackSmartAppBannerDisplay(name);var closeButton=document.querySelector(".sb-container .sb-cell-close-btn a");if(closeButton!==null)Bootstrapper.unobtrusiveAddEvent(closeButton,
"ontouchstart",function(){Bootstrapper.analytics.bannerTracking.trackSmartAppBannerAction(name,"Close")});var actionButton=document.querySelector(".sb-container .sb-cell-content a");if(actionButton!==null)Bootstrapper.unobtrusiveAddEvent(actionButton,"ontouchstart",function(){Bootstrapper.analytics.bannerTracking.trackSmartAppBannerAction(name,actionButton.innerHTML)})}}},3E3)},708719,[708717],292958,[292957]);
Bootstrapper.bindDependencyImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;mboxCopyright="Copyright 1996-2014. Adobe Systems Incorporated. All rights reserved.";window.TNT=window.TNT||{};TNT.a=TNT.a||{};TNT.a.nestedMboxes=[];TNT.a.isDomLoaded=false;TNT.getGlobalMboxName=function(){return"target-global-mbox"};TNT.getGlobalMboxLocation=function(){return""};TNT.isAutoCreateGlobalMbox=function(){return false};TNT.getClientMboxExtraParameters=
function(){return""};TNT.a.b=function(){var c={}.toString;var d=window.targetPageParams;var e=null;if(typeof d==="undefined"||c.call(d)!=="[object Function]")return[];try{e=d()}catch(f){}if(e===null)return[];if(c.call(e)==="[object Array]")return e;if(c.call(e)==="[object String]"&&e.length>0){var g=e.split("\x26");for(var h=0;h<g.length;h++){if(g[h].indexOf("\x3d")<=0){g.splice(h,1);continue}g[h]=decodeURIComponent(g[h])}return g}if(c.call(e)==="[object Object]")return TNT.a.i([],e);return[]};TNT.a.i=
function(j,k){var l=[];var m=j.join(".");var n=undefined;for(o in k){if(!k.hasOwnProperty(o))continue;n=k[o];if(typeof n==="object"){j.push(o);var p=TNT.a.i(j,n);j.pop();for(var h=0;h<p.length;h++)l.push(p[h]);continue}l.push((m.length>0?m+".":"")+o+"\x3d"+n)}return l};mboxUrlBuilder=function(q,r){this.q=q;this.r=r;this.s=new Array;this.t=function(u){return u};this.v=null};mboxUrlBuilder.prototype.addNewParameter=function(w,x){this.s.push({name:w,value:x});return this};mboxUrlBuilder.prototype.addParameterIfAbsent=
function(w,x){if(x){for(var y=0;y<this.s.length;y++){var z=this.s[y];if(z.name===w)return this}this.checkInvalidCharacters(w);return this.addNewParameter(w,x)}};mboxUrlBuilder.prototype.addParameter=function(w,x){this.checkInvalidCharacters(w);for(var y=0;y<this.s.length;y++){var z=this.s[y];if(z.name===w){z.value=x;return this}}return this.addNewParameter(w,x)};mboxUrlBuilder.prototype.addParameters=function(s){if(!s)return this;for(var y=0;y<s.length;y++){var A=s[y].indexOf("\x3d");if(A==-1||A==
0)continue;this.addParameter(s[y].substring(0,A),s[y].substring(A+1,s[y].length))}return this};mboxUrlBuilder.prototype.setServerType=function(B){this.C=B};mboxUrlBuilder.prototype.setBasePath=function(v){this.v=v};mboxUrlBuilder.prototype.setUrlProcessAction=function(D){this.t=D};mboxUrlBuilder.prototype.buildUrl=function(){var E=this.v?this.v:"/m2/"+this.r+"/mbox/"+this.C;var F=document.location.protocol=="file:"?"http:":document.location.protocol;var u=F+"//"+this.q+E;var G=u.indexOf("?")!=-1?
"\x26":"?";for(var y=0;y<this.s.length;y++){var z=this.s[y];u+=G+encodeURIComponent(z.name)+"\x3d"+encodeURIComponent(z.value);G="\x26"}return this.H(this.t(u))};mboxUrlBuilder.prototype.getParameters=function(){return this.s};mboxUrlBuilder.prototype.setParameters=function(s){this.s=s};mboxUrlBuilder.prototype.clone=function(){var I=new mboxUrlBuilder(this.q,this.r);I.setServerType(this.C);I.setBasePath(this.v);I.setUrlProcessAction(this.t);for(var y=0;y<this.s.length;y++)I.addParameter(this.s[y].name,
this.s[y].value);return I};mboxUrlBuilder.prototype.H=function(J){return J.replace(/\"/g,"\x26quot;").replace(/>/g,"\x26gt;")};mboxUrlBuilder.prototype.checkInvalidCharacters=function(w){var K=new RegExp("('|\")");if(K.exec(w))throw"Parameter '"+w+"' contains invalid characters";};mboxStandardFetcher=function(){};mboxStandardFetcher.prototype.getType=function(){return"standard"};mboxStandardFetcher.prototype.fetch=function(L){L.setServerType(this.getType());document.write("\x3c"+"scr"+'ipt src\x3d"'+
L.buildUrl()+'" language\x3d"JavaScript"\x3e\x3c'+"/scr"+"ipt\x3e")};mboxStandardFetcher.prototype.cancel=function(){};mboxAjaxFetcher=function(){};mboxAjaxFetcher.prototype.getType=function(){return"ajax"};mboxAjaxFetcher.prototype.fetch=function(L){L.setServerType(this.getType());var u=L.buildUrl();this.M=document.createElement("script");this.M.src=u;document.body.appendChild(this.M)};mboxAjaxFetcher.prototype.cancel=function(){};mboxMap=function(){this.N=new Object;this.O=new Array};mboxMap.prototype.put=
function(P,x){if(!this.N[P])this.O[this.O.length]=P;this.N[P]=x};mboxMap.prototype.get=function(P){return this.N[P]};mboxMap.prototype.remove=function(P){this.N[P]=undefined;var Q=[];for(var i=0;i<this.O.length;i++)if(this.O[i]!==P)Q.push(this.O[i]);this.O=Q};mboxMap.prototype.each=function(D){for(var y=0;y<this.O.length;y++){var P=this.O[y];var x=this.N[P];if(x){var l=D(P,x);if(l===false)break}}};mboxMap.prototype.isEmpty=function(){return this.O.length===0};mboxFactory=function(R,r,S){this.T=false;
this.R=R;this.S=S;this.U=new mboxList;mboxFactories.put(S,this);this.V=typeof document.createElement("div").replaceChild!="undefined"&&function(){return true}()&&typeof document.getElementById!="undefined"&&typeof(window.attachEvent||document.addEventListener||window.addEventListener)!="undefined"&&typeof encodeURIComponent!="undefined";this.W=this.V&&mboxGetPageParameter("mboxDisable")==null;var X=S=="default";this.Y=new mboxCookieManager("mbox"+(X?"":"-"+S),function(){return mboxCookiePageDomain()}());
this.W=this.W&&this.Y.isEnabled()&&this.Y.getCookie("disable")==null;if(this.isAdmin())this.enable();this.Z();this._=mboxGenerateId();this.ab=mboxScreenHeight();this.bb=mboxScreenWidth();this.cb=mboxBrowserWidth();this.db=mboxBrowserHeight();this.eb=mboxScreenColorDepth();this.fb=mboxBrowserTimeOffset();this.gb=new mboxSession(this._,"mboxSession","session",31*60,this.Y);this.hb=new mboxPC("PC",1209600,this.Y);this.L=new mboxUrlBuilder(R,r);this.ib(this.L,X);this.jb=(new Date).getTime();this.kb=this.jb;
var lb=this;this.addOnLoad(function(){lb.kb=(new Date).getTime()});if(this.V){this.addOnLoad(function(){lb.T=true;lb.getMboxes().each(function(mb){mb.nb();mb.setFetcher(new mboxAjaxFetcher);mb.finalize()});TNT.a.nestedMboxes=[];TNT.a.isDomLoaded=true});if(this.W){this.limitTraffic(100,10368E3);this.ob();this.pb=new mboxSignaler(function(qb,s){return lb.create(qb,s)},this.Y)}}};mboxFactory.prototype.isEnabled=function(){return this.W};mboxFactory.prototype.getDisableReason=function(){return this.Y.getCookie("disable")};
mboxFactory.prototype.isSupported=function(){return this.V};mboxFactory.prototype.disable=function(rb,sb){if(typeof rb=="undefined")rb=60*60;if(typeof sb=="undefined")sb="unspecified";if(!this.isAdmin()){this.W=false;this.Y.setCookie("disable",sb,rb)}};mboxFactory.prototype.enable=function(){this.W=true;this.Y.deleteCookie("disable")};mboxFactory.prototype.isAdmin=function(){return document.location.href.indexOf("mboxEnv")!=-1};mboxFactory.prototype.limitTraffic=function(tb,rb){};mboxFactory.prototype.addOnLoad=
function(ub){if(this.isDomLoaded())ub();else{var vb=false;var wb=function(){if(vb)return;vb=true;ub()};this.xb.push(wb);if(this.isDomLoaded()&&!vb)wb()}};mboxFactory.prototype.getEllapsedTime=function(){return this.kb-this.jb};mboxFactory.prototype.getEllapsedTimeUntil=function(yb){return yb-this.jb};mboxFactory.prototype.getMboxes=function(){return this.U};mboxFactory.prototype.get=function(qb,zb){return this.U.get(qb).getById(zb||0)};mboxFactory.prototype.update=function(qb,s){if(!this.isEnabled())return;
if(!this.isDomLoaded()){var lb=this;this.addOnLoad(function(){lb.update(qb,s)});return}if(this.U.get(qb).length()==0)throw"Mbox "+qb+" is not defined";this.U.get(qb).each(function(mb){mb.getUrlBuilder().addParameter("mboxPage",mboxGenerateId());mboxFactoryDefault.setVisitorIdParameters(mb.getUrlBuilder(),qb);mb.load(s)})};mboxFactory.prototype.setVisitorIdParameters=function(u,qb){var imsOrgId="";if(typeof Visitor=="undefined"||imsOrgId.length==0)return;var visitor=Visitor.getInstance(imsOrgId);if(visitor.isAllowed()){var addVisitorValueToUrl=
function(param,getter,mboxName){if(visitor[getter]){var callback=function(value){if(value)u.addParameter(param,value)};var value;if(typeof mboxName!="undefined")value=visitor[getter]("mbox:"+mboxName);else value=visitor[getter](callback);callback(value)}};addVisitorValueToUrl("mboxMCGVID","getMarketingCloudVisitorID");addVisitorValueToUrl("mboxMCGLH","getAudienceManagerLocationHint");addVisitorValueToUrl("mboxAAMB","getAudienceManagerBlob");addVisitorValueToUrl("mboxMCAVID","getAnalyticsVisitorID");
addVisitorValueToUrl("mboxMCSDID","getSupplementalDataID",qb)}};mboxFactory.prototype.create=function(qb,s,Ab){if(!this.isSupported())return null;var u=this.L.clone();u.addParameter("mboxCount",this.U.length()+1);u.addParameters(s);this.setVisitorIdParameters(u,qb);var zb=this.U.get(qb).length();var Bb=this.S+"-"+qb+"-"+zb;var Cb;if(Ab)Cb=new mboxLocatorNode(Ab);else{if(this.T)throw"The page has already been loaded, can't write marker";Cb=new mboxLocatorDefault(Bb)}try{var lb=this;var Db="mboxImported-"+
Bb;var mb=new mbox(qb,zb,u,Cb,Db);if(this.W)mb.setFetcher(this.T?new mboxAjaxFetcher:new mboxStandardFetcher);mb.setOnError(function(Eb,B){mb.setMessage(Eb);mb.activate();if(!mb.isActivated()){lb.disable(60*60,Eb);window.location.reload(false)}});this.U.add(mb)}catch(Fb){this.disable();throw'Failed creating mbox "'+qb+'", the error was: '+Fb;}var Gb=new Date;u.addParameter("mboxTime",Gb.getTime()-Gb.getTimezoneOffset()*6E4);return mb};mboxFactory.prototype.getCookieManager=function(){return this.Y};
mboxFactory.prototype.getPageId=function(){return this._};mboxFactory.prototype.getPCId=function(){return this.hb};mboxFactory.prototype.getSessionId=function(){return this.gb};mboxFactory.prototype.getSignaler=function(){return this.pb};mboxFactory.prototype.getUrlBuilder=function(){return this.L};mboxFactory.prototype.ib=function(u,X){u.addParameter("mboxHost",document.location.hostname).addParameter("mboxSession",this.gb.getId());if(!X)u.addParameter("mboxFactoryId",this.S);if(this.hb.getId()!=
null)u.addParameter("mboxPC",this.hb.getId());u.addParameter("mboxPage",this._);u.addParameter("screenHeight",this.ab);u.addParameter("screenWidth",this.bb);u.addParameter("browserWidth",this.cb);u.addParameter("browserHeight",this.db);u.addParameter("browserTimeOffset",this.fb);u.addParameter("colorDepth",this.eb);u.setUrlProcessAction(function(u){u+="\x26mboxURL\x3d"+encodeURIComponent(document.location);var Hb=encodeURIComponent(document.referrer);if(u.length+Hb.length<2E3)u+="\x26mboxReferrer\x3d"+
Hb;u+="\x26mboxVersion\x3d"+mboxVersion;return u})};mboxFactory.prototype.Ib=function(){return""};mboxFactory.prototype.ob=function(){document.write("\x3cstyle\x3e."+"mboxDefault"+" { visibility:hidden; }\x3c/style\x3e")};mboxFactory.prototype.isDomLoaded=function(){return this.T};mboxFactory.prototype.Z=function(){if(this.xb!=null)return;this.xb=new Array;var lb=this;(function(){var Jb=document.addEventListener?"DOMContentLoaded":"onreadystatechange";var Kb=false;var Lb=function(){if(Kb)return;Kb=
true;for(var i=0;i<lb.xb.length;++i)lb.xb[i]()};if(document.addEventListener){document.addEventListener(Jb,function(){document.removeEventListener(Jb,arguments.callee,false);Lb()},false);window.addEventListener("load",function(){document.removeEventListener("load",arguments.callee,false);Lb()},false)}else if(document.attachEvent)if(self!==self.top)document.attachEvent(Jb,function(){if(document.readyState==="complete"){document.detachEvent(Jb,arguments.callee);Lb()}});else{var Mb=function(){try{document.documentElement.doScroll("left");
Lb()}catch(Nb){setTimeout(Mb,13)}};Mb()}if(document.readyState==="complete")Lb()})()};mboxSignaler=function(Ob,Y){this.Y=Y;var Pb=Y.getCookieNames("signal-");for(var y=0;y<Pb.length;y++){var Qb=Pb[y];var Rb=Y.getCookie(Qb).split("\x26");var mb=Ob(Rb[0],Rb);mb.load();Y.deleteCookie(Qb)}};mboxSignaler.prototype.signal=function(Sb,qb){this.Y.setCookie("signal-"+Sb,mboxShiftArray(arguments).join("\x26"),45*60)};mboxList=function(){this.U=new Array};mboxList.prototype.add=function(mb){if(mb!=null)this.U[this.U.length]=
mb};mboxList.prototype.get=function(qb){var l=new mboxList;for(var y=0;y<this.U.length;y++){var mb=this.U[y];if(mb.getName()==qb)l.add(mb)}return l};mboxList.prototype.getById=function(h){return this.U[h]};mboxList.prototype.length=function(){return this.U.length};mboxList.prototype.each=function(D){if(typeof D!=="function")throw"Action must be a function, was: "+typeof D;for(var y=0;y<this.U.length;y++)D(this.U[y])};mboxLocatorDefault=function(w){this.w="mboxMarker-"+w;document.write('\x3cdiv id\x3d"'+
this.w+'" style\x3d"visibility:hidden;display:none"\x3e\x26nbsp;\x3c/div\x3e')};mboxLocatorDefault.prototype.locate=function(){var Tb=document.getElementById(this.w);while(Tb!=null){if(Tb.nodeType==1)if(Tb.className=="mboxDefault")return Tb;Tb=Tb.previousSibling}return null};mboxLocatorDefault.prototype.force=function(){var Ub=document.createElement("div");Ub.className="mboxDefault";var Vb=document.getElementById(this.w);if(Vb)Vb.parentNode.insertBefore(Ub,Vb);return Ub};mboxLocatorNode=function(Wb){this.Tb=
Wb};mboxLocatorNode.prototype.locate=function(){return typeof this.Tb=="string"?document.getElementById(this.Tb):this.Tb};mboxLocatorNode.prototype.force=function(){return null};mboxCreate=function(qb){var mb=mboxFactoryDefault.create(qb,mboxShiftArray(arguments));if(mb)mb.load();return mb};mboxDefine=function(Ab,qb){var mb=mboxFactoryDefault.create(qb,mboxShiftArray(mboxShiftArray(arguments)),Ab);return mb};mboxUpdate=function(qb){mboxFactoryDefault.update(qb,mboxShiftArray(arguments))};mbox=function(w,
Xb,L,Yb,Db){this.Zb=null;this._b=0;this.Cb=Yb;this.Db=Db;this.ac=null;this.bc=new mboxOfferContent;this.Ub=null;this.L=L;this.message="";this.cc=new Object;this.dc=0;this.Xb=Xb;this.w=w;this.ec();L.addParameter("mbox",w).addParameter("mboxId",Xb);this.fc=function(){};this.gc=function(){};this.hc=null;this.ic=document.documentMode>=10&&!TNT.a.isDomLoaded;if(this.ic){this.jc=TNT.a.nestedMboxes;this.jc.push(this.w)}};mbox.prototype.getId=function(){return this.Xb};mbox.prototype.ec=function(){if(this.w.length>
250)throw"Mbox Name "+this.w+" exceeds max length of "+"250 characters.";else if(this.w.match(/^\s+|\s+$/g))throw"Mbox Name "+this.w+" has leading/trailing whitespace(s).";};mbox.prototype.getName=function(){return this.w};mbox.prototype.getParameters=function(){var s=this.L.getParameters();var l=new Array;for(var y=0;y<s.length;y++)if(s[y].name.indexOf("mbox")!=0)l[l.length]=s[y].name+"\x3d"+s[y].value;return l};mbox.prototype.setOnLoad=function(D){this.gc=D;return this};mbox.prototype.setMessage=
function(Eb){this.message=Eb;return this};mbox.prototype.setOnError=function(fc){this.fc=fc;return this};mbox.prototype.setFetcher=function(kc){if(this.ac)this.ac.cancel();this.ac=kc;return this};mbox.prototype.getFetcher=function(){return this.ac};mbox.prototype.load=function(s){if(this.ac==null)return this;this.setEventTime("load.start");this.cancelTimeout();this._b=0;var L=s&&s.length>0?this.L.clone().addParameters(s):this.L;this.ac.fetch(L);var lb=this;this.lc=setTimeout(function(){lb.fc("browser timeout",
lb.ac.getType())},15E3);this.setEventTime("load.end");return this};mbox.prototype.loaded=function(){this.cancelTimeout();if(!this.activate()){var lb=this;setTimeout(function(){lb.loaded()},100)}};mbox.prototype.activate=function(){if(this._b)return this._b;this.setEventTime("activate"+ ++this.dc+".start");if(this.ic&&this.jc[this.jc.length-1]!==this.w)return this._b;if(this.show()){this.cancelTimeout();this._b=1}this.setEventTime("activate"+this.dc+".end");if(this.ic)this.jc.pop();return this._b};
mbox.prototype.isActivated=function(){return this._b};mbox.prototype.setOffer=function(bc){if(bc&&bc.show&&bc.setOnLoad)this.bc=bc;else throw"Invalid offer";return this};mbox.prototype.getOffer=function(){return this.bc};mbox.prototype.show=function(){this.setEventTime("show.start");var l=this.bc.show(this);this.setEventTime(l==1?"show.end.ok":"show.end");return l};mbox.prototype.showContent=function(mc){if(mc==null)return 0;if(this.Ub==null||!this.Ub.parentNode){this.Ub=this.getDefaultDiv();if(this.Ub==
null)return 0}if(this.Ub!=mc){this.nc(this.Ub);this.Ub.parentNode.replaceChild(mc,this.Ub);this.Ub=mc}this.oc(mc);this.gc();return 1};mbox.prototype.hide=function(){this.setEventTime("hide.start");var l=this.showContent(this.getDefaultDiv());this.setEventTime(l==1?"hide.end.ok":"hide.end.fail");return l};mbox.prototype.finalize=function(){this.setEventTime("finalize.start");this.cancelTimeout();if(this.getDefaultDiv()==null)if(this.Cb.force()!=null)this.setMessage("No default content, an empty one has been added");
else this.setMessage("Unable to locate mbox");if(!this.activate()){this.hide();this.setEventTime("finalize.end.hide")}this.setEventTime("finalize.end.ok")};mbox.prototype.cancelTimeout=function(){if(this.lc)clearTimeout(this.lc);if(this.ac!=null)this.ac.cancel()};mbox.prototype.getDiv=function(){return this.Ub};mbox.prototype.getDefaultDiv=function(){if(this.hc==null)this.hc=this.Cb.locate();return this.hc};mbox.prototype.setEventTime=function(pc){this.cc[pc]=(new Date).getTime()};mbox.prototype.getEventTimes=
function(){return this.cc};mbox.prototype.getImportName=function(){return this.Db};mbox.prototype.getURL=function(){return this.L.buildUrl()};mbox.prototype.getUrlBuilder=function(){return this.L};mbox.prototype.qc=function(Ub){return Ub.style.display!="none"};mbox.prototype.oc=function(Ub){this.rc(Ub,true)};mbox.prototype.nc=function(Ub){this.rc(Ub,false)};mbox.prototype.rc=function(Ub,sc){Ub.style.visibility=sc?"visible":"hidden";Ub.style.display=sc?"block":"none"};mbox.prototype.nb=function(){this.ic=
false};mbox.prototype.relocateDefaultDiv=function(){this.hc=this.Cb.locate()};mboxOfferContent=function(){this.gc=function(){}};mboxOfferContent.prototype.show=function(mb){var l=mb.showContent(document.getElementById(mb.getImportName()));if(l==1)this.gc();return l};mboxOfferContent.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferAjax=function(mc){this.mc=mc;this.gc=function(){}};mboxOfferAjax.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferAjax.prototype.show=function(mb){var tc=document.createElement("div");
tc.id=mb.getImportName();tc.innerHTML=this.mc;var l=mb.showContent(tc);if(l==1)this.gc();return l};mboxOfferDefault=function(){this.gc=function(){}};mboxOfferDefault.prototype.setOnLoad=function(gc){this.gc=gc};mboxOfferDefault.prototype.show=function(mb){var l=mb.hide();if(l==1)this.gc();return l};mboxCookieManager=function mboxCookieManager(w,uc){this.w=w;this.uc=uc==""||uc.indexOf(".")==-1?"":"; domain\x3d"+uc;this.vc=new mboxMap;this.loadCookies()};mboxCookieManager.prototype.isEnabled=function(){this.setCookie("check",
"true",60);this.loadCookies();return this.getCookie("check")=="true"};mboxCookieManager.prototype.setCookie=function(w,x,rb){if(typeof w!="undefined"&&typeof x!="undefined"&&typeof rb!="undefined"){var wc=new Object;wc.name=w;wc.value=escape(x);wc.expireOn=Math.ceil(rb+(new Date).getTime()/1E3);this.vc.put(w,wc);this.saveCookies()}};mboxCookieManager.prototype.getCookie=function(w){var wc=this.vc.get(w);return wc?unescape(wc.value):null};mboxCookieManager.prototype.deleteCookie=function(w){this.vc.remove(w);
this.saveCookies()};mboxCookieManager.prototype.getCookieNames=function(xc){var yc=new Array;this.vc.each(function(w,wc){if(w.indexOf(xc)==0)yc[yc.length]=w});return yc};mboxCookieManager.prototype.saveCookies=function(){var zc=false;var Ac="disable";var Bc=new Array;var Cc=0;this.vc.each(function(w,wc){if(!zc||w===Ac){Bc[Bc.length]=w+"#"+wc.value+"#"+wc.expireOn;if(Cc<wc.expireOn)Cc=wc.expireOn}});var Dc=new Date(Cc*1E3);document.cookie=this.w+"\x3d"+Bc.join("|")+"; expires\x3d"+Dc.toGMTString()+
"; path\x3d/"+this.uc};mboxCookieManager.prototype.loadCookies=function(){this.vc=new mboxMap;var Ec=document.cookie.indexOf(this.w+"\x3d");if(Ec!=-1){var Fc=document.cookie.indexOf(";",Ec);if(Fc==-1){Fc=document.cookie.indexOf(",",Ec);if(Fc==-1)Fc=document.cookie.length}var Gc=document.cookie.substring(Ec+this.w.length+1,Fc).split("|");var Hc=Math.ceil((new Date).getTime()/1E3);for(var y=0;y<Gc.length;y++){var wc=Gc[y].split("#");if(Hc<=wc[2]){var Ic=new Object;Ic.name=wc[0];Ic.value=wc[1];Ic.expireOn=
wc[2];this.vc.put(Ic.name,Ic)}}}};mboxSession=function(Jc,Kc,Qb,Lc,Y){this.Kc=Kc;this.Qb=Qb;this.Lc=Lc;this.Y=Y;this.Mc=false;this.Xb=typeof mboxForceSessionId!="undefined"?mboxForceSessionId:mboxGetPageParameter(this.Kc);if(this.Xb==null||this.Xb.length==0){this.Xb=Y.getCookie(Qb);if(this.Xb==null||this.Xb.length==0){this.Xb=Jc;this.Mc=true}}Y.setCookie(Qb,this.Xb,Lc)};mboxSession.prototype.getId=function(){return this.Xb};mboxSession.prototype.forceId=function(Nc){this.Xb=Nc;this.Y.setCookie(this.Qb,
this.Xb,this.Lc)};mboxPC=function(Qb,Lc,Y){this.Qb=Qb;this.Lc=Lc;this.Y=Y;this.Xb=typeof mboxForcePCId!="undefined"?mboxForcePCId:Y.getCookie(Qb);if(this.Xb!=null)Y.setCookie(Qb,this.Xb,Lc)};mboxPC.prototype.getId=function(){return this.Xb};mboxPC.prototype.forceId=function(Nc){if(this.Xb!=Nc){this.Xb=Nc;this.Y.setCookie(this.Qb,this.Xb,this.Lc);return true}return false};mboxGetPageParameter=function(w){var l=null;var Oc=new RegExp("\\?[^#]*"+w+"\x3d([^\x26;#]*)");var Pc=Oc.exec(document.location);
if(Pc!=null&&Pc.length>=2)l=Pc[1];return l};mboxSetCookie=function(w,x,rb){return mboxFactoryDefault.getCookieManager().setCookie(w,x,rb)};mboxGetCookie=function(w){return mboxFactoryDefault.getCookieManager().getCookie(w)};mboxCookiePageDomain=function(){var uc=/([^:]*)(:[0-9]{0,5})?/.exec(document.location.host)[1];var Qc=/[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}/;if(!Qc.exec(uc)){var Rc=/([^\.]+\.[^\.]{3}|[^\.]+\.[^\.]+\.[^\.]{2})$/.exec(uc);if(Rc){uc=Rc[0];if(uc.indexOf("www.")==0)uc=uc.substr(4)}}return uc?
uc:""};mboxShiftArray=function(Sc){var l=new Array;for(var y=1;y<Sc.length;y++)l[l.length]=Sc[y];return l};mboxGenerateId=function(){return(new Date).getTime()+"-"+Math.floor(Math.random()*999999)};mboxScreenHeight=function(){return screen.height};mboxScreenWidth=function(){return screen.width};mboxBrowserWidth=function(){return window.innerWidth?window.innerWidth:document.documentElement?document.documentElement.clientWidth:document.body.clientWidth};mboxBrowserHeight=function(){return window.innerHeight?
window.innerHeight:document.documentElement?document.documentElement.clientHeight:document.body.clientHeight};mboxBrowserTimeOffset=function(){return-(new Date).getTimezoneOffset()};mboxScreenColorDepth=function(){return screen.pixelDepth};if(typeof mboxVersion=="undefined"){mboxVersion=55;mboxFactories=new mboxMap;mboxFactoryDefault=new mboxFactory("williamhill.tt.omtrdc.net","williamhill","default")}if(mboxGetPageParameter("mboxDebug")!=null||mboxFactoryDefault.getCookieManager().getCookie("debug")!=
null){setTimeout(function(){if(typeof mboxDebugLoaded=="undefined")alert("Could not load the remote debug.\nPlease check your connection"+" to Test\x26amp;Target servers")},60*60);document.write("\x3c"+"scr"+'ipt language\x3d"Javascript1.2" src\x3d'+'"//admin7.testandtarget.omniture.com/admin/mbox/mbox_debug.jsp?mboxServerHost\x3dwilliamhill.tt.omtrdc.net'+'\x26clientCode\x3dwilliamhill"\x3e\x3c'+"/scr"+"ipt\x3e")}mboxScPluginFetcher=function(r,Tc){this.r=r;this.Tc=Tc};mboxScPluginFetcher.prototype.Uc=
function(L){L.setBasePath("/m2/"+this.r+"/sc/standard");this.Vc(L);var u=L.buildUrl();u+="\x26scPluginVersion\x3d1";return u};mboxScPluginFetcher.prototype.Vc=function(L){var Wc=["dynamicVariablePrefix","visitorID","vmk","ppu","charSet","visitorNamespace","cookieDomainPeriods","cookieLifetime","pageName","currencyCode","variableProvider","channel","server","pageType","transactionID","purchaseID","campaign","state","zip","events","products","linkName","linkType","resolution","colorDepth","javascriptVersion",
"javaEnabled","cookiesEnabled","browserWidth","browserHeight","connectionType","homepage","pe","pev1","pev2","pev3","visitorSampling","visitorSamplingGroup","dynamicAccountSelection","dynamicAccountList","dynamicAccountMatch","trackDownloadLinks","trackExternalLinks","trackInlineStats","linkLeaveQueryString","linkDownloadFileTypes","linkExternalFilters","linkInternalFilters","linkTrackVars","linkTrackEvents","linkNames","lnk","eo"];for(var y=0;y<Wc.length;y++)this.Xc(Wc[y],L);for(var y=1;y<=75;y++){this.Xc("prop"+
y,L);this.Xc("eVar"+y,L);this.Xc("hier"+y,L)}};mboxScPluginFetcher.prototype.Xc=function(w,L){var x=this.Tc[w];if(typeof x==="undefined"||x===null||x===""||typeof x==="object")return;L.addParameter(w,x)};mboxScPluginFetcher.prototype.cancel=function(){};mboxScPluginFetcher.prototype.fetch=function(L){L.setServerType(this.getType());var u=this.Uc(L);this.M=document.createElement("script");this.M.src=u;document.body.appendChild(this.M)};mboxScPluginFetcher.prototype.getType=function(){return"ajax"};
window.mboxLoadSCPlugin=function(Tc){if(!Tc)return null;Tc.m_tt=function(Tc){var Yc=Tc.m_i("tt");Yc.W=true;Yc.r="williamhill";Yc["_t"]=function(){if(!this.isEnabled())return;var mb=this._c();if(mb){var kc=new mboxScPluginFetcher(this.r,this.s);mb.setFetcher(kc);mb.load()}};Yc.isEnabled=function(){return this.W&&mboxFactoryDefault.isEnabled()};Yc._c=function(){var qb=this.ad();var Ub=document.createElement("DIV");return mboxFactoryDefault.create(qb,new Array,Ub)};Yc.ad=function(){var bd=this.s.events&&
this.s.events.indexOf("purchase")!=-1;return"SiteCatalyst: "+(bd?"purchase":"event")}};return Tc.loadModule("tt")};mboxVizTargetUrl=function(qb){if(!mboxFactoryDefault.isEnabled())return;var L=mboxFactoryDefault.getUrlBuilder().clone();L.setBasePath("/m2/"+"williamhill"+"/viztarget");L.addParameter("mbox",qb);L.addParameter("mboxId",0);L.addParameter("mboxCount",mboxFactoryDefault.getMboxes().length()+1);var Gb=new Date;L.addParameter("mboxTime",Gb.getTime()-Gb.getTimezoneOffset()*6E4);L.addParameter("mboxPage",
mboxGenerateId());var s=mboxShiftArray(arguments);if(s&&s.length>0)L.addParameters(s);L.addParameter("mboxDOMLoaded",mboxFactoryDefault.isDomLoaded());mboxFactoryDefault.setVisitorIdParameters(L,qb);return L.buildUrl()};TNT.createGlobalMbox=function(){var cd="target-global-mbox";var dd="".length===0;var ed="";var fd;if(dd){ed="mbox-"+cd+"-"+mboxGenerateId();fd=document.createElement("div");fd.className="mboxDefault";fd.id=ed;fd.style.visibility="hidden";fd.style.display="none";mboxFactoryDefault.addOnLoad(function(){document.body.insertBefore(fd,
document.body.firstChild)})}var gd=mboxFactoryDefault.create(cd,TNT.a.b(),ed);if(gd!=null)gd.load()};Bootstrapper.MVT.addModule("tt",{init:function(){},swap:function(a,b){if(typeof mboxFactoryDefault=="undefined"||!mboxFactoryDefault.isEnabled()){Bootstrapper.MVT.show(a,b);_log("*** MVT:show - T\x26T disabled");_log(a);_log(b)}else{_log("*** MVT:loaded");_log(a);_log(b);var i="_ensMbox"+(1E3*Math.random()).toFixed(0),f,p,o=!1;if(b.a=="replace"){o=!0;if(!!a.tagName.toUpperCase().match(/DIV/)){if(!~a.className.indexOf("mboxDefault"))a.className=
a.className+" mboxDefault";if(a.id!="")i=a.id;else a.id=i}else if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA|BR/))a.innerHTML='\x3cdiv id\x3d"'+i+'" class\x3d"mboxDefault"\x3e'+a.innerHTML+"\x3c/div\x3e";else{b.a="element";setTimeout(function(){Bootstrapper.MVT.swap(a,b)},1);return}}else{d=document.createElement("div");d.id=i;d.className="mboxDefault";d.style.visibility="hidden";if(b.a=="prepend"){if(a.firstChild!==null)a.insertBefore(d,a.firstChild);Bootstrapper.MVT.done()}else if(b.a=="append")a.appendChild(d,
a);else if(b.a=="element"||typeof b.a=="undefined"){o=!0;var c=a.cloneNode(!0);d.appendChild(c);if(a.parentNode!==null)a.parentNode.replaceChild(d,a)}else if(b.a=="before"){if(a.parentNode!==null)a.parentNode.insertBefore(d,a)}else if(b.a=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling)}f=b.p||{};p=[];for(k in f)p.push(k+"\x3d"+f[k]);var m=window.mboxDefine(i,b.i);p.unshift(b.i);window.mboxUpdate.apply(m,p);m=window.mboxFactories.get("default").get(b.i)||
{};m._show=m.show;m.show=function(b,m){return function(){var r=m._show.call(m);if(r)Bootstrapper.MVT.show(!1,b);return r}}(b,m)}}});elementOnLoad=function(e,l){var m=document.getElementById(e);if(m){l(m);m.style.display="block"}else setTimeout(function(){elementOnLoad(e,l)},20)},elementAddEvent=function(a){var d=document,w=window,wa=w.addEventListener,da=d.addEventListener,e="load",o="on"+e;if(wa)wa(e,a,false);else if(da)da(e,a,false);else if(d.attachEvent)w.attachEvent(o,a)};elementAddEvent(function(){elementOnLoad=
function(){}});if(typeof jQuery!="undefined")(function($){var c=function(s,f){if($(s)[0])try{f.apply($(s)[0])}catch(e){setTimeout(function(){c(s,f)},1)}else setTimeout(function(){c(s,f)},1)};if($.isReady)setTimeout("c\x3dfunction(){}",100);$.fn.elementOnLoad=function(f){c(this.selector,f)}})(jQuery)},853017,[853020],289632,[148384]);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;window.trk_get_settings=function(){var mode="live";var omnt_settings={it:{dev:["whg-it-mobile-dev","metrics.williamhill.it","smetrics.williamhill.it"],live:["whg-it-mobile-prod","metrics.williamhill.it","smetrics.williamhill.it"]},es:{dev:["whg-es-mobile-dev","metrics.williamhill.es","smetrics.williamhill.es"],live:["whg-es-mobile-prod","metrics.williamhill.es","smetrics.williamhill.es"]},
com:{dev:["whg-intl-mobile-dev","metrics.williamhill.com","smetrics.williamhill.com"],live:["whg-intl-mobile-prod","metrics.williamhill.com","smetrics.williamhill.com"]},failover:{dev:["whg-failover-all","williamhill.com.d3.sc.omtrdc.net","williamhill.com.ssl.d3.sc.omtrdc.net"]}};var domain=document.domain.split(".");tld=domain[domain.length-1];site=domain[domain.length-2];if(site!="williamhill")mode="dev";return tld=="com"||tld=="es"||tld=="it"?omnt_settings[tld][mode]:omnt_settings.failover.dev}},
587275,151305);
Bootstrapper.bindImmediate(function(){var Bootstrapper=window["Bootstrapper"];var ensightenOptions=Bootstrapper.ensightenOptions;Bootstrapper.AF=[];Bootstrapper.analytics={init:true};Bootstrapper.analytics.sportsBook={init:true};Bootstrapper.analytics.clearSObject=function(sArray){for(var i=0;i<=75;i++){s["prop"+i]="";s["eVar"+i]=""}if(sArray)for(var a=0;a<sArray.length;a++)s[sArray[a]]=""};Bootstrapper.ajaxListener=function(){var listeners={},listener=function(a,b){var detected=[],selector=a||function(){},
attach=b||function(node){};return function(){if(typeof selector=="function"&&typeof attach=="function"){var n=selector();if(typeof n=="object")if(typeof n.length!="undefined"){n=Array.prototype.slice.call(n,0);for(var i=n.length-1;i>=0;i--)for(var j=0;j<detected.length;j++)if(n[i]==detected[j])n.splice(i,1);for(var i=0;i<n.length;detected.push(n[i++]));for(var i=0;i<n.length;attach.call(n[i],n[i++]));}else{for(var i=0;i<detected.length;i++)if(n==detected[i])return;detected.push(n);attach.call(n,n)}}}},
_public={create:function(x,y){do var a=parseInt(Math.random()*1E5)+"";while(listeners[a]);listeners[a]=listener(x,y)}};setInterval(function(){for(key in listeners)listeners[key]()},500);return _public}();Bootstrapper.getElementsByClassName=function(){var root=document,className="",partial=false;for(var i=0;i<arguments.length;i++)if(typeof arguments[i]=="object")root=arguments[i];else if(typeof arguments[i]=="string")className=arguments[i];else partial=arguments[i];var elements=root.getElementsByTagName("*");
var retElements=[],needle=partial?new RegExp(className):new RegExp("^"+className+"$");for(var i=0;i<elements.length;i++)if(typeof elements[i].className=="string"){var tempClass=elements[i].className||"";if(tempClass.match(needle))retElements.push(elements[i])}return retElements};Bootstrapper.getCookie=function(c_name){var c_value=document.cookie;var c_start=c_value.indexOf(" "+c_name+"\x3d");if(c_start==-1)c_start=c_value.indexOf(c_name+"\x3d");if(c_start==-1)c_value=null;else{c_start=c_value.indexOf("\x3d",
c_start)+1;var c_end=c_value.indexOf(";",c_start);if(c_end==-1)c_end=c_value.length;c_value=unescape(c_value.substring(c_start,c_end))}return c_value};Bootstrapper.setCookie=function(c_name,value,exdays){var domain_split=location.hostname.split(".");var domain=domain_split[domain_split.length-2]+"."+domain_split[domain_split.length-1];var exdate=new Date;exdate.setDate(exdate.getDate()+exdays);var c_value=escape(value)+(exdays==null?"":"; expires\x3d"+exdate.toUTCString());document.cookie=c_name+
"\x3d"+c_value+";domain\x3d."+domain+";path\x3d/"};Bootstrapper.searchUpDOM=function(elem,attribute){while(elem.tagName!=="BODY"){if(elem.getAttribute(attribute))return elem.getAttribute(attribute);elem=elem.parentNode}return""};Bootstrapper.changeAttributeDetails=function(element,attribute,value,addRemove){addRemove=addRemove?addRemove:"add";var curr_props="";var has_existing_tag=true;try{curr_props=element.getAttribute(attribute).split(/\s+/)}catch(err){has_existing_tag=false;curr_props=[""]}var new_props=
value.split(/\s+/);for(var i=0;i<new_props.length;i++)for(var j=0;j<curr_props.length;j++)if(new_props[i]==curr_props[j]){new_props[i]="";if(addRemove=="remove")curr_props[j]=""}var altered_props=(addRemove=="remove"?curr_props:curr_props.concat(new_props)).join(" ").replace(/\s+/g," ").replace(/(^\s|\s$)/,"");if(altered_props==""||altered_props==" "){if(has_existing_tag)return element.removeAttribute(attribute)}else return element.setAttribute(attribute,altered_props)};Bootstrapper.dataManager=function(){var _private=
{data:{},sanitize:function(fn,id){_fn=fn+"";if(typeof fn=="function"&&/Bootstrapper\.dataManager\.getData/.test(_fn))return function(){return""};else if(typeof fn=="function")return fn},add:function(o){if(typeof o=="object"&&o.id){o.get=function(e){return Bootstrapper.dataManager.getDataElement(this.id,e)};for(var k in o.data){o.data[k].get=this.sanitize(o.data[k].get,o.id)||o.data[k].get;o.data[k].mod=this.sanitize(o.data[k].mod,o.id)||o.data[k].mod}this.data[o.id]=o}},getObj:function(i){if(i)return _private.data[i];
return _private.data},getDataElement:function(i,e){var dataObj=this.data[i].data,retVal;if(typeof dataObj=="object"){dataObj=dataObj[e];if(typeof dataObj.get=="string"){var d=eval(dataObj.get);if(typeof dataObj.mod=="string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}else if(typeof dataObj.get=="function"){var d=dataObj.get.call(this.data[i]);if(typeof dataObj.mod==
"string"&&dataObj.mod!==""){var m="(function(){ return "+(dataObj.mod===""?"this":dataObj.mod)+";})";retVal=eval(m).call(d)}else if(typeof dataObj.mod=="function")retVal=dataObj.mod.call(d,d);else retVal=d}return retVal}},getDataLayer:function(i){var retObj={};var dataObj=this.data[i].data;for(key in dataObj)try{retObj[key]=this.getDataElement(i,key)}catch(e){retObj[key]=null}return retObj},getAllData:function(){var data=this.data,retObj={_d:{}};for(var key in data){retObj._d[key]={};var d=this.getDataLayer(key);
for(var k in d){retObj[k]=d[k];retObj._d[key][k]=d[k]}}return retObj},getData:function(i){if(i)return this.getDataLayer(i);else return this.getAllData()},addDataElement:function(layerId,name,o){if(typeof this.data[layerId]=="object"&&typeof name=="string"&&typeof o=="object"){var d=this.data[layerId];d.data[name]=o}}},_public={push:function(dl){_private.add(dl)},getObj:function(i){return _private.getObj(i)},getData:function(i){return _private.getData(i)},getDataElement:function(i,e){return _private.getDataElement(i,
e)},addDataElement:function(layerId,name,o){return _private.addDataElement(layerId,name,o)}};return _public}();Bootstrapper.Cookies=function(){return{domain:function(){return function(){var a=location.hostname.split(".");var b=[a[1],a[2]];var c=b.join(".");return c}()}()||location.hostname,get:function(a,c){for(var b=document.cookie.split(";"),d=0;d<b.length;d++){var e=b[d].replace(/^\s+/,"").split("\x3d");if(e[0]==a)return c?e[1]:decodeURIComponent(e[1])}return""},set:function(a,c,b){document.cookie=
a+"\x3d"+encodeURIComponent(c)+(b?";expires\x3d"+b:"")+";path\x3d/;domain\x3d"+this.domain;return this.get(a)==c},test:function(a){return this.get(a)?!0:!1}}}();Bootstrapper.propertyWatcher=function(options){var _private={watchers:[]},_public={};_private.options=options||{};_private.options.interval=_private.options.interval||50;_private.Watcher=function(propertyFn,options){var _public={};_public.propertyFn=propertyFn;_public.lastValue=undefined;_public.options=options;_public.change=function(oldVal,
newVal){};return _public};_private.doChecks=function(){for(var i=0;i<_private.watchers.length;i++){var w=_private.watchers[i],p=w.propertyFn?w.propertyFn():null;if(w.lastValue!=p){w.change(w.lastValue,p);w.lastValue=p}}_private.resetTimer()};_private.resetTimer=function(){window.setTimeout(function(){_private.doChecks()},_private.options.interval)};_private.addWatcher=function(fn,options){var w=_private.Watcher(fn,options);_private.watchers.push(w);return w};_public={create:_private.addWatcher};_private.doChecks();
return _public}();Bootstrapper.getElementXPath=function(e){var n=e;var p="";while(n!=document.getElementsByTagName("html")[0]){var t="/"+n.tagName;if(n.id!=""){t+="#"+n.id;p=t+p}else{var c=1;_n=n.previousSibling;while(_n!=null){if(n.tagName==_n.tagName)c++;_n=_n.previousSibling}p=t+(c!=1?"["+c+"]":"")+p}n=n.parentNode}return Bootstrapper.getMinXPath("/HTML"+p)};Bootstrapper.getMinXPath=function(path){var p=path.split("/"),lastId=0;for(var i=0;i<p.length;i++)if(~p[i].indexOf("#"))lastId=i;for(var i=
lastId-1;i>0;i--)if(!p[i].match(/^(html|body)/i))p.splice(i,1);return p.join("/")};Bootstrapper.getElementByXPathStep=function(d,a){var c=~a.indexOf("#")?a.split("#")[1]:"",e=c?0:~a.indexOf("[")?parseInt(a.match(/\[(\d+)\]/)[1]):0,f=(c?a.split("#")[0]:e?a.split("[")[0]:a).toLowerCase();if(d==document&&f=="html"&&e==0)return document.getElementsByTagName("html")[0];if(~a.indexOf("#"))return document.getElementById(a.split("#")[1]);var b=d.firstChild;if(!b)return null;for(var g=0,e=e!=0?e-1:e;b;){if(b.nodeType==
1)if(b.tagName.toLowerCase()==f&&c!=""&&b.id==c)return b;else if(b.tagName.toLowerCase()==f&&g==e&&c=="")return b;else b.tagName.toLowerCase()==f&&g++;b=b.nextSibling}};Bootstrapper.getElementByXPath=function(d,n){for(var d=d.split("/"),a=Bootstrapper.getElementByXPathStep(n||document,d[1]),c=2;c<d.length;c++){if(a==null)return null;a=Bootstrapper.getElementByXPathStep(a,d[c])}return a};window._log=function(m){window._enslog=window._enslog||[];window._enslog.push(m);if(console){var v=typeof m=="string"?
m:"",s=window.location.search,p=~s.indexOf("ensightenDebug\x3d")?s.split("ensightenDebug\x3d")[1].split("\x26")[0].split("#")[0].split(";")[0]:!1;if(p&&p=="act"){if(~v.indexOf("$$$"))console.log(v)}else if(p&&p=="cloak"){if(~v.indexOf("*** Cloak"))console.log(v)}else if(p)console.log(m)}};Bootstrapper.MVT=function(){var g={},h={split:function(b,a){var c=[];do{var d=b.shift(),e=[],f=[d];(e=d.x.split("/")).shift();for(d=b.length-1;-1<d;d--){var g=b[d].x.split("/");g.shift();g[0]==e[0]&&(f.push(b[d]),
b.splice(d,1))}c.push(f)}while(0<b.length);for(d=0;d<c.length;d++)e=this.getCommon(c[d]),Bootstrapper.MVT.traverse(a,e,c[d])},getCommon:function(b){for(var a=[],c=0;c<b.length;a.push(b[c++].x));if(1==a.length)return a[0];for(c=0;c<a.length;(a[c]=a[c++].split("/")).shift());b=a[0];for(c=1;c<a.length;c++){for(var d=0;d<a[c].length;d++)if(a[0][d]!=a[c][d]){var e=d;break}if(e)break}return"/"+b.slice(0,e).join("/")},tests:[]},i={hidden:[],cloaks:[],EDLutils:!0,initialized:!1,invisibilityCloak:!1,disabled:!!~window.location.search.indexOf("ensTools\x3ddisable"),
cloakDisabled:(true||!!~window.location.search.indexOf("ensCloak\x3ddisable"))&&!~window.location.search.indexOf("ensCloak\x3denable"),forceSyncCloak:!!~window.location.search.indexOf("ensCloak\x3d")&&!!~window.location.search.indexOf("!resync"),content:{initialized:!1,map:{},list:"",target:function(o){if(typeof o=="string"&&~o.indexOf("##")&&~o.indexOf("@@"))this.store(o);else{if(o instanceof Array){var c="";for(var i=0,l=o.length;i<l;i++)if(o[i].u)c+="##"+o[i].u+"@@"+(o[i].x||"")}else if(o.u)o=
"##"+o.u+"@@"+(o.x||"");this.store(o)}},utils:function(a,n,o){if(Bootstrapper.data)try{if(a=="get")return Bootstrapper.data.getEngine("store").utils.get(n);else if(a=="set")return Bootstrapper.data.getEngine("store").utils.set(n,o)}catch(e){Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL utils not available")}else{Bootstrapper.MVT.EDLutils=false;_log("*** Cloak:EDL not available")}},store:function(o){if(!Bootstrapper.MVT.content.initialized)this.list=o;else{if(this.list=="")this.list=o;this.utils("set",
"_ensCloak",o)}_log("*** Cloak:Storage updated")},load:function(d){var cl;if(d==1)cl=this.list;else cl=this.utils("get","_ensCloak");if(!d){_log("GLOBAL: "+this.list);_log("STORED: "+cl)}if(typeof cl=="string"&&cl!=""&&~cl.indexOf("##")){cl=cl.split("##");for(var i=0,l=cl.length;i<l;i++)if(~cl[i].indexOf("@@")){var u=cl[i].split("@@")[0],x=cl[i].split("@@")[1]||"";if(d=="list"){_log("URL: "+u);_log("XPATH: "+x)}this.add({"u":u,"x":x})}_log("*** Cloak:Storage loaded")}else _log("*** Cloak:Storage empty")},
add:function(o){if(o.u){if(~window.location.href.indexOf(o.u))if(o.x&&o.x!=""){if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}}else Bootstrapper.MVT.invisibilityCloak=true}else if(typeof this.map[o.x]=="undefined"){this.map[o.x]=o;this.map[o.x].t="map"}},init:function(){if(!Bootstrapper.MVT.cloakDisabled){var sync=this.utils("get","_ensCloakSync")||"",time=(new Date).getTime(),fetch=true;if(Bootstrapper.MVT.EDLutils){if(~sync!=""&&!isNaN(sync))if(time-sync>18E5)sync=time;
else fetch=false;else sync=time;if(fetch)this.utils("set","_ensCloakSync",sync)}else fetch=false;if(fetch||Bootstrapper.MVT.forceSyncCloak){if(Bootstrapper.scDataObj)Bootstrapper.scDataObj["ensCloak"]="sync";if(this.list=="")Bootstrapper.MVT.invisibilityCloak=true;_log("*** Cloak:Syncing")}this.load(1);this.load(2)}var m=this.map;for(i in m)if(m[i].x)Bootstrapper.MVT.push({x:m[i].x,m:m[i].x,t:"map"});if(Bootstrapper.MVT.invisibilityCloak&&!Bootstrapper.MVT.disabled&&!Bootstrapper.MVT.cloakDisabled)Bootstrapper.MVT.cover()}},
addModule:function(b,a){g[b]=a},swap:function(b,a){g[a.t].swap(b,a)},start:function(b){for(var a=0;a<b.length;a++)g[b[a].t].init(b[a]);a=h.getCommon(b);"/"==a&&h.split(b,document);this.traverse(document,a,b)},init:function(){Bootstrapper.MVT.content.initialized=!0;Bootstrapper.MVT.content.init();_log("*** MVT:init - "+h.tests.length+" targets");Bootstrapper.MVT.initialized=!0;_log(h.tests.slice());if(h.tests.length&&!this.disabled)Bootstrapper.MVT.start(h.tests)},push:function(o){if(Bootstrapper.MVT.disabled)return;
if(typeof o=="object"){_log("*** MVT:push");_log(o);if(typeof this.setDone=="undefined"){this.setDone=1;Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.done()});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.done()},500)})}if(o.x){o.cloak=this.cloak(o,1);if(o.t&&this.content.map[o.x])if(o.t=="map")this.content.map[o.x].cloak=o.cloak;else if(this.content.map[o.x].cloak)Bootstrapper.MVT.delCSS(this.content.map[o.x].cloak)}if(this.initialized&&o.x){_log("MVT:content");
_log(o);if(this.content.map[o.x])for(i in o)this.content.map[o.x][i]=o[i];else this.check(o)}else{for(var i=0;i<h.tests.length;i++)if(h.tests[i].x&&o.x&&h.tests[i].x==o.x)if(h.tests[i].t=="map"&&o.t!="map"){for(j in o)h.tests[i][j]=o[j];return}h.tests.push(o);this.hidden.push(o)}}},injectCSS:function(x,e){var d=document,s=d.createElement("style");if(e)s.className="_ensCSS";if("\v"=="v"){d.getElementsByTagName("head")[0].appendChild(s);s.styleSheet.cssText=x}else{s.type="text/css";s.innerHTML=x;d.getElementsByTagName("head")[0].appendChild(s)}return s},
delCSS:function(s,f){if(s)try{if("\v"=="v")s.styleSheet.cssText="/**/";if(s.parentNode)s.parentNode.removeChild(s);return!0}catch(e){if(f)return f();return!1}return!1},cover:function(){_log("*** Cloak:Cover");this.invisibilityCloak=this.injectCSS("body{position:relative; opacity:0 !important;filter:alpha(opacity\x3d0) !important;background:none !important}");Bootstrapper.bindPageSpecificCompletion(function(){Bootstrapper.MVT.uncover("Uncover - complete")});Bootstrapper.bindDOMLoaded(function(){setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - loaded")},
500)});setTimeout(function(){Bootstrapper.MVT.uncover("Uncover - timeout")},7E3)},uncover:function(l){if(this.invisibilityCloak)if(this.delCSS(this.invisibilityCloak)){this.invisibilityCloak=!1;_log("*** Cloak:"+l)}},cloak:function(o,t){var s=false,x=o.toString();if(typeof o=="object"&&o.x)x=o.x;if(~x.indexOf("/HTML/"))x=x.substr(1).replace(/\//g," ").replace(/\[.*\]$/g,"");s=Bootstrapper.MVT.injectCSS(x+"{visibility:hidden !important}",t);if(t)this.cloaks.push(s);return s},show:function(a,b){if(b&&
b.cloak)this.delCSS(b.cloak);else if(a){a.style.display=a.style.oldDisplay||"block";a.style.visibility="visible"}},done:function(){var a=this.hidden,c=this.cloaks,s=document.getElementsByTagName("style");for(i=0;i<h.length;i++)this.show(h[i]);this.hidden=[];for(i=0;i<c.length;i++)this.delCSS(c[i]);this.cloaks=[];for(i=0;i<s.length;i++)if(s[i].className=="_ensCSS")this.delCSS(s[i]);_log("*** MVT:done")},check:function(o){var n=Bootstrapper.getElementByXPath(o.x);_log("*** MVT:check");_log(n);if(n)Bootstrapper.MVT.swap(n,
o);else if(!Bootstrapper.hasDOMLoaded())setTimeout(function(){Bootstrapper.MVT.check(o)},25);else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found")}},traverse:function(b,a,c){if(1==c.length&&c[0].x==a)var d=!0;for(var e=0;e<c.length;c[e].x=c[e++].x.slice(a.length));(a=a.split("/")).shift();for(e=0;e<a.length;e++){var f=Bootstrapper.getElementByXPathStep(b,a[e]);if(null!=f){Bootstrapper.swapNodes=Bootstrapper.swapNodes||[];Bootstrapper.swapNodes.push(f);b=f}else{a=
"/"+a.slice(e).join("/");for(e=0;e<c.length;c[e].x=a+c[e++].x);if(!Bootstrapper.hasDOMParsed()){setTimeout(function(a,b,c){return function(){Bootstrapper.MVT.traverse(a,b,c)}}(b,a,c),25);return}else{setTimeout(function(){Bootstrapper.MVT.done()},100);_log("*** MVT:unresolved - not found");return}}}d?this.swap(b,c[0]):h.split(c,b)}};return i}();Bootstrapper.bindOnGetServerComponent(function(){Bootstrapper.MVT.init()});Bootstrapper.MVT.addModule("map",{init:function(a){},swap:function(a,b){if(typeof Bootstrapper.DOMloadedDone==
"undefined"||!Bootstrapper.DOMloadedDone){if(Bootstrapper.hasDOMLoaded()&&typeof Bootstrapper.DOMloadedDone=="undefined"){Bootstrapper.DOMloadedDone=!1;_log("*** DOM:loaded ***");setTimeout(function(){Bootstrapper.DOMloadedDone=!0},500)}if(Bootstrapper.MVT.content.map[b.m].t!="map"){for(i in Bootstrapper.MVT.content.map[b.m])b[i]=Bootstrapper.MVT.content.map[b.m][i];Bootstrapper.MVT.swap(a,b);return}else{setTimeout(function(){Bootstrapper.MVT.swap(a,b)},10);return}}else{_log("*** MVT:show - no changes found \x3d "+
b.m);Bootstrapper.MVT.show(a,b)}}});Bootstrapper.MVT.addModule("xp",{init:function(a){},swap:function(a,b){_log("*** MVT:loaded");_log(a);_log(b);var d=0;if(b.p=="replace"){if(!a.tagName.toUpperCase().match(/IMG|INPUT|TEXTAREA/)){a.innerHTML=b.c;a.className=a.className+" ensContent";d=a}}else{d=document.createElement("div");d.className="ensContent";d.innerHTML=b.c;if(b.p=="prepend")if(a.firstChild!==null)a.insertBefore(d,a.firstChild);else d=0;else if(b.p=="append")a.appendChild(d,a);else if(b.p==
"element")if(a.parentNode!==null)a.parentNode.replaceChild(d,a);else d=0;else if(b.p=="before")if(a.parentNode!==null)a.parentNode.insertBefore(d,a);else d=0;else if(b.p=="after")if(a.parentNode!==null)if(a.nextSibling===null)a.parentNode.appendChild(d);else a.parentNode.insertBefore(d,a.nextSibling);else d=0}try{if(d)for(var s=d.getElementsByTagName("script"),l=s.length,i=0;i<l;i++)if(s[i].src){var l=document.createElement("script");l.src=s[i].src;l.type=s[i].type;s[i].parentNode.replaceChild(d,
s[i])}else Function("try{"+s[i].text+"}catch(e){}")()}catch(e){}_log("*** MVT:complete");Bootstrapper.MVT.show(a,b)}});Bootstrapper.VTconfig=Bootstrapper.VTconfig||{};Bootstrapper.VTconfig["MVT"]=this.deploymentId},853020,148384);Bootstrapper.getServerComponent(Bootstrapper.getExtraParams ? Bootstrapper.getExtraParams() : undefined);}})();